# Generated by Django 5.0.6 on 2024-06-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
