# Generated by Django 5.0.6 on 2024-06-13 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_remove_carro_categoria_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_pagamento', models.DateTimeField()),
                ('foto_produto', models.ImageField(upload_to='perfil/')),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.cadastro')),
            ],
        ),
    ]
