# Generated by Django 5.0.6 on 2024-06-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='nome',
        ),
    ]
