# Generated by Django 5.0.6 on 2024-06-13 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_remove_pagamento_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='foto_produto',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='carro',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='carros.carro'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='tipo_de_pagamento',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='cadastro',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='carros.cadastro'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateField(),
        ),
    ]
