# Generated by Django 5.0.6 on 2024-06-13 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0006_remove_pagamento_foto_produto_pagamento_carro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carro',
            name='imagem',
            field=models.ImageField(upload_to='foto_perfil/'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.cadastro'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.carro'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='tipo_de_pagamento',
            field=models.CharField(max_length=100),
        ),
    ]
