# Generated by Django 5.0.6 on 2024-06-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0008_carro_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='Celular',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
