# Generated by Django 5.0.6 on 2024-06-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0009_cadastro_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='cadastro',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='carro',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='data_pagamento',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='valor',
        ),
    ]
