# Generated by Django 5.0.6 on 2024-05-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_avaliacao_data_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='data_venda',
        ),
    ]
