# Generated by Django 5.0.6 on 2024-07-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magalu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='data_produto',
            new_name='imagem_produto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
