# Generated by Django 5.0.6 on 2024-05-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='book_perfil/'),
        ),
    ]
