# Generated by Django 5.0.6 on 2024-05-22 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_publicacao', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='book_perfil/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.author')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
