# Generated by Django 5.0.6 on 2024-05-17 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='Cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='Produtos',
            new_name='produtos',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
