# Generated by Django 5.0.6 on 2024-06-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamaha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='carro',
            new_name='moto',
        ),
    ]
