# Generated by Django 5.0.6 on 2024-05-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=100)),
                ('nome_filme', models.CharField(max_length=100)),
                ('filme_status', models.CharField(choices=[('Y', 'ja assistir'), ('N', 'Não assistir')], max_length=2)),
                ('valor_filme', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': '@utor',
                'verbose_name_plural': '@utores',
                'ordering': ('pk',),
            },
        ),
    ]
