# Generated by Django 5.0.6 on 2024-05-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.CharField(default='aguardando editora', max_length=50),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ano_publicado',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
