# Generated by Django 5.0.6 on 2024-05-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_livro_editora_alter_livro_ano_publicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='editora2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(default='Bloomsbury Publishing', max_length=50),
        ),
    ]
